-- Insert sample data into the Menu table with updated categories
INSERT INTO Menu (Category, Name, Price)
VALUES 
('Appetizer', 'Caesar Salad', 7.99),
('Main Course', 'Grilled Chicken', 15.50),
('Dessert', 'Chocolate Cake', 6.25),
('Main Course', 'Margherita Pizza', 12.00),
('Beverage', 'Lemonade', 3.50),
('Dessert', 'Tiramisu', 7.00),
('Main Course', 'Pasta Alfredo', 13.75),
('Beverage', 'Cappuccino', 4.25),
('Appetizer', 'Garlic Bread', 5.50),
('Beverage', 'Orange Juice', 3.25),
('Dessert', 'Cheesecake', 6.50),
('Main Course', 'Fish Tacos', 14.50),
('Beverage', 'Iced Tea', 2.75),
('Appetizer', 'Bruschetta', 6.50),
('Main Course', 'Beef Stroganoff', 17.00),
('Dessert', 'Apple Pie', 5.00),
('Beverage', 'Sparkling Water', 2.00),
('Main Course', 'Vegetable Stir Fry', 11.50),
('Appetizer', 'Stuffed Mushrooms', 8.00),
('Dessert', 'Panna Cotta', 6.75),
('Beverage', 'Hot Chocolate', 3.75),
('Appetizer', 'Spinach Dip', 7.25),
('Main Course', 'Lamb Chops', 22.00),
('Dessert', 'Brownie Sundae', 7.50),
('Beverage', 'Mint Mojito', 4.50),
('Main Course', 'Shrimp Scampi', 19.00),
('Appetizer', 'Chicken Wings', 9.00),
('Dessert', 'Lemon Tart', 6.00),
('Beverage', 'Peach Iced Tea', 3.25),
('Appetizer', 'Caprese Salad', 8.50),
('Main Course', 'Pork Tenderloin', 18.50),
('Dessert', 'Pavlova', 6.75),
('Beverage', 'Berry Smoothie', 4.00),
('Main Course', 'Quinoa Salad', 12.00),
('Appetizer', 'Fish Ceviche', 9.50),
('Dessert', 'Mango Sticky Rice', 5.75),
('Beverage', 'Lemon Basil Soda', 3.50),
('Appetizer', 'Onion Rings', 5.00),
('Main Course', 'Baked Ziti', 14.00),
('Dessert', 'Fruit Salad', 4.50),
('Beverage', 'Apple Cider', 3.00),
('Main Course', 'Chicken Alfredo', 15.00),
('Appetizer', 'Pork Sliders', 9.00),
('Dessert', 'Chocolate Mousse', 7.25),
('Beverage', 'Coconut Water', 2.50),
('Main Course', 'Eggplant Parmesan', 14.50),
('Appetizer', 'Nachos', 8.00),
('Dessert', 'Key Lime Pie', 6.00),
('Beverage', 'Raspberry Lemonade', 3.75),
('Main Course', 'Turkey Burger', 13.00),
('Appetizer', 'Meatballs', 8.50),
('Dessert', 'Vanilla Ice Cream', 4.00),
('Beverage', 'Fizzy Lemonade', 2.75),
('Main Course', 'Seafood Paella', 20.00),
('Appetizer', 'Antipasto Platter', 10.00),
('Dessert', 'Chocolate Chip Cookies', 5.25),
('Beverage', 'Ginger Ale', 2.50);
